-- QUESTIONS -- 
-- 1.	Combien d’employés sont actuellement actifs ? : REP = 1300 

	SELECT 
	COUNT (ID_EMPLOYE) 
	AS NBR_EMPL_ACTIF
	FROM EMPLOYES 
	WHERE DATE_DEPART IS NULL 
	
-- 2.	Combien de départs avons-nous eu sur les 12 derniers mois ? REP = 144

	SELECT 
	COUNT (*)  
	AS DEPART_12_MOIS 
	FROM TURNOVER 
	WHERE DATE_DEPART <= CURRENT_DATE - INTERVAL '12 MONTHS'
	
	>=  
-- 3.	Quels sont les départements ayant le turnover le plus élevé
	-- c'est à dire, les departements ayant observé beaucoup plus de depart?  
	-- Il s'agit donc de compter les departs par departement -- 
	
	SELECT 
		D.NOM_DEPARTEMENT,
		COUNT (T.ID_DEPART) 
		AS TURNOVER_ELEVE 
	FROM TURNOVER T 
	JOIN EMPLOYES E ON T.ID_EMPLOYE = E.ID_EMPLOYE
	JOIN DEPARTEMENTS D ON E.ID_DEPARTEMENT = D.ID_DEPARTEMENT
	GROUP BY D.NOM_DEPARTEMENT 
	ORDER BY TURNOVER_ELEVE 
	DESC 
	
-- 4.	Quel est le salaire moyen par département ? --

	SELECT NOM_DEPARTEMENT, 
		ROUND (AVG (E.SALAIRE), 2) 
		AS SALAIRE_MOYEN 
	FROM EMPLOYES E 
	JOIN DEPARTEMENTS D 
		ON D.ID_DEPARTEMENT = E.ID_DEPARTEMENT 
	GROUP BY NOM_DEPARTEMENT 
	ORDER BY SALAIRE_MOYEN 
	DESC 

-- 5.	Quels sont les employés qui ont plus de 5 années d’ancienneté ? -- 

	SELECT 
		E.ID_EMPLOYE, 
		E.NOM, 
		E.PRENOM, 
		T.ANCIENNETE
	FROM EMPLOYES E 
	JOIN TURNOVER T 
		ON E.ID_EMPLOYE = T.ID_EMPLOYE 
	WHERE T.ANCIENNETE > 5 	
	GROUP BY 
		E.ID_EMPLOYE, 
		E.NOM, 
		E.PRENOM, 
		T.ANCIENNETE 
	ORDER BY ANCIENNETE  
	DESC
	
-- 6.	Classez les départements par performance moyenne trimestrielle. -- 

	SELECT D.NOM_DEPARTEMENT, 
		ROUND (AVG (P.SCORE),2) 
		AS PERFORM_MOYEN_TRI 
	FROM PERFORMANCES P 
	JOIN EMPLOYES E 
		ON E.ID_EMPLOYE = P.ID_EMPLOYE 
	JOIN DEPARTEMENTS D 
		ON E.ID_DEPARTEMENT = D.ID_DEPARTEMENT 
	GROUP BY D.NOM_DEPARTEMENT 
	ORDER BY PERFORM_MOYEN_TRI 
	DESC 
	
-- 7.1.	Identifier les 10 meilleurs employés sur les 3 derniers trimestres. --

	SELECT E.ID_EMPLOYE, D.NOM_DEPARTEMENT,
		ROUND (AVG (P.SCORE),2)
		AS TOP_DIX_SCORE_MOYEN_TRI
	FROM PERFORMANCES P 
		JOIN EMPLOYES E ON E.ID_EMPLOYE = P.ID_EMPLOYE 
		JOIN DEPARTEMENTS D ON D.ID_DEPARTEMENT = E.ID_DEPARTEMENT 
	GROUP BY E.ID_EMPLOYE, D.NOM_DEPARTEMENT
	ORDER BY TOP_DIX_SCORE_MOYEN_TRI 
	DESC 
	LIMIT 10 

-- 7.2.	Identifier les 10 meilleurs employés sur les 3 derniers trimestres. --

	
	SELECT E.ID_EMPLOYE, D.NOM_DEPARTEMENT,
		COUNT (P.SCORE)
		AS TOP_DIX_SCORE_NBRE_TRI
	FROM PERFORMANCES P 
		JOIN EMPLOYES E ON E.ID_EMPLOYE = P.ID_EMPLOYE 
		JOIN DEPARTEMENTS D ON D.ID_DEPARTEMENT = E.ID_DEPARTEMENT 
	GROUP BY E.ID_EMPLOYE, D.NOM_DEPARTEMENT
	ORDER BY TOP_DIX_SCORE_NBRE_TRI 
	DESC 
	LIMIT 10 

-- 8.	Identifier les employés les moins performants et leur département. --

	SELECT E.ID_EMPLOYE, D.NOM_DEPARTEMENT,
		ROUND (AVG (P.SCORE),2)
		AS SCORES_MOINS_PERFOR
	FROM PERFORMANCES P 
		JOIN EMPLOYES E ON E.ID_EMPLOYE = P.ID_EMPLOYE 
		JOIN DEPARTEMENTS D ON D.ID_DEPARTEMENT = E.ID_DEPARTEMENT 
	GROUP BY E.ID_EMPLOYE, D.NOM_DEPARTEMENT
	HAVING ROUND (AVG (P.SCORE),2) < 60   
	ORDER BY SCORES_MOINS_PERFOR 
	ASC 
-- 9.	Calculer la rétention moyenne par cohorte d’embauche. -- 

	SELECT 
		COHORTE_EMBAUCHES ,
		ROUND (AVG (ANCIENNETES),2)
		AS ANCIENNETE_MOYENNE
	FROM EMPLOYES 
	GROUP BY COHORTE_EMBAUCHES
	ORDER BY COHORTE_EMBAUCHES
	DESC 
	
-- 10.	Quels départements recrutent le plus souvent ? 

	SELECT 
			D.NOM_DEPARTEMENT,  
			COUNT (E.COHORTE_EMBAUCHES)
			AS NBRE_EMBAUCHE 
	FROM EMPLOYES E 
		JOIN DEPARTEMENTS D
			ON E.ID_DEPARTEMENT = D.ID_DEPARTEMENT 
	GROUP BY NOM_DEPARTEMENT 
	ORDER BY NBRE_EMBAUCHE 
	DESC 

-- 11.	Quelle proportion des départs est volontaire vs involontaire ? 

	SELECT 
			TYPE_DEPART, 
			COUNT (*) 
			AS NBRE_DEPART, 
		ROUND (COUNT (*) * 100 / SUM (COUNT(*)) 
			OVER(), 2 )
			AS POURCENTAGE 
	FROM TURNOVER 
	GROUP BY TYPE_DEPART			
	
-- 12.	Quelle est la distribution des postes par ancienneté ? -- 

	SELECT DISTINCT (E.POSTE), 
	SUM (T.ANCIENNETE)
	AS DISTRIBUTION
	FROM EMPLOYES E 
	JOIN TURNOVER T ON E.ID_EMPLOYE = T.ID_EMPLOYE 
	GROUP BY E.POSTE 
	ORDER BY DISTRIBUTION 
	DESC 

-- DISTRIBUTION AVEC UTILISATION DES INTERVALLES --

	SELECT DISTINCT (POSTE), 
		CASE 
			WHEN ANCIENNETES <  2 THEN '0-2 ANS'
			WHEN ANCIENNETES BETWEEN 2 AND 5 THEN '2-5 ANS'
					ELSE '5 ANS ET +'
		END AS TRANCHE_ANCIENNETE, 
			COUNT (*) AS NBRE_EMPLOYE 
	FROM EMPLOYES 
	GROUP BY POSTE, TRANCHE_ANCIENNETE 
	ORDER BY POSTE, TRANCHE_ANCIENNETE 

-- 13.	Quels employés n’ont pas encore reçu de feedback cette année ? -- 

	SELECT 
			E.ID_EMPLOYE, 
			E.NOM, 
			E.PRENOM 
	FROM EMPLOYES E 
		JOIN PERFORMANCES P 
			ON E.ID_EMPLOYE = P.ID_EMPLOYE
			AND EXTRACT (YEAR FROM P.DATE_EVALUATION) = EXTRACT (YEAR FROM CURRENT_DATE) 
	WHERE P.ID_EMPLOYE IS NULL 		
	AND E.DATE_DEPART IS NULL 
	

	SELECT 
			E.ID_EMPLOYE, 
			E.NOM, 
			E.PRENOM 
	FROM EMPLOYES E 
	 		
	WHERE E.DATE_DEPART IS NULL 

-- 14.	Segmentez les employés par niveau de performance : faible / moyen / élevé. --

	SELECT 
		CATEGORIE_PERFORMANCE,
		COUNT (*)
		AS NBRE_EMPLOYES 
	FROM PERFORMANCE_CATEGORIE 
	GROUP BY CATEGORIE_PERFORMANCE 
	ORDER BY NBRE_EMPLOYES 
	DESC

-- 15.	Générer un tableau résumé avec KPIs par département et par cohorte. -- 

 	SELECT 
	 	D.NOM_DEPARTEMENT,
	 	E.COHORTE_EMBAUCHES,
	 	COUNT (E.ID_EMPLOYE) AS EFFECTIF, 
		ROUND (AVG (E.SALAIRE), 2) AS SALAIRE_MOYEN, 
		ROUND (AVG (P.SCORE), 2) AS SCORE_MOYEN, 
		ROUND (AVG (E.ANCIENNETES), 2) AS ANCIENNETE_MOYENNE
	FROM EMPLOYES E
		JOIN DEPARTEMENTS D 
			ON E.ID_DEPARTEMENT = D.ID_DEPARTEMENT 
		LEFT JOIN PERFORMANCES P 
			ON E.ID_EMPLOYE = P.ID_EMPLOYE 
		GROUP BY D.NOM_DEPARTEMENT, E.COHORTE_EMBAUCHES 
		ORDER BY D.NOM_DEPARTEMENT, E.COHORTE_EMBAUCHES



	
	  