
-- STYLE DE DATE EN JOUR-MOIS-ANNEE -- 

	SET DATESTYLE = 'SQL, EUROPEAN'

-- ENRICHISSEMENT DES DONNEES --
-- AJOUT DE LA COLONNE ANCIENNETES A LA TABLE EMPOLYES -- 

	ALTER TABLE EMPLOYES 
	ADD COLUMN ANCIENNETES INTEGER 

-- CALCUL DU NOMBRE D'ANNEES D'ANCIENNETE DANS LA TABLE EMPLOYES -- 

	UPDATE EMPLOYES 
	SET ANCIENNETES = EXTRACT (YEAR FROM AGE (COALESCE(DATE_DEPART, 
						DATE_EMBAUCHE),  
						DATE_EMBAUCHE)) WHERE DATE_DEPART IS NOT NULL;

	UPDATE EMPLOYES 
	SET ANCIENNETES = EXTRACT (YEAR FROM AGE (COALESCE(DATE_DEPART, 
						DATE_EMBAUCHE),  
						DATE_EMBAUCHE));

-- CREATION DE LA COLONNE COHORTE_EMBAUCHE --

	ALTER TABLE EMPLOYES 
	ADD COLUMN COHORTE_EMBAUCHES INTEGER ; 

-- EXTRACTION DE L'ANNEE DANS LE CHAMP COHORTE_EMBAUCHE -- 
	
	UPDATE EMPLOYES 
	SET COHORTE_EMBAUCHES = EXTRACT (YEAR FROM DATE_EMBAUCHE)

--  CREATION D'UNE VUE ET CALCUL DU SCORE MOYEN PAR EMPLOYE -- 

	CREATE VIEW PERFORM_MOY AS 
	SELECT 
			ID_EMPLOYE, 
			ROUND (AVG(SCORE), 2)
			AS SCORE_MOYEN 
	FROM PERFORMANCES 
	GROUP BY ID_EMPLOYE

-- CATEGORIE DE PERFORMANCE AVEC CREATION DE VUE -- 

	CREATE VIEW PERFORMANCE_CATEGORIE AS 
	SELECT 
			P.ID_EMPLOYE, 
			P.SCORE, 
		CASE 
			WHEN P.SCORE < 60 THEN 'FAIBLE'
			WHEN P.SCORE BETWEEN 60 AND 80 THEN 'MOYENNE' 
			ELSE 'ELEVEE' 
		END AS CATEGORIE_PERFORMANCE 
	FROM PERFORMANCES P ;

	
	
	