-- Database: PROJET_2

-- DROP DATABASE IF EXISTS "PROJET_2";

CREATE DATABASE "PROJET_2"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'French_Togo.1252'
    LC_CTYPE = 'French_Togo.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

	
	-- FORMATAE DU STYLE DE DATE EN JOUR-MOIS-ANNEE -- 

	 SET DATESTYLE = 'SQL, EUROPEAN'
	
	-- CREATION DES TABLES -- 
	-- CREATION DE LA TABLE DEPARTEMENTS -- 

	CREATE TABLE DEPARTEMENTS  
		(
		id_departement SERIAL PRIMARY KEY NOT NULL,	
		nom_departement	VARCHAR (100),
		manager	VARCHAR (100), 
		budget NUMERIC
		) ;

	SELECT * 
	FROM DEPARTEMENTS 
	
	-- CREATION DE LA TABLE EMPLOYES -- 

	CREATE TABLE EMPLOYES 
		(
		id_employe SERIAL PRIMARY KEY NOT NULL, 	
		nom VARCHAR (50),	
		prenom VARCHAR (50),
		poste VARCHAR (50), 
		ID_departement INT  REFERENCES DEPARTEMENTS (ID_DEPARTEMENT),
		date_embauche DATE, 
		date_depart DATE,	
		salaire NUMERIC
		); 

	SELECT * 
	FROM EMPLOYES 
	
	-- CREATION DE LA TABLE PERFORMENCES --  
	
	CREATE TABLE PERFORMANCES 
		(
		id_performance SERIAL PRIMARY KEY NOT NULL, 	
		id_employe INT REFERENCES EMPLOYES (ID_EMPLOYE), 
		date_evaluation DATE, 	
		score INT, 
		objectifs_atteints VARCHAR (20)
		);
	
	SELECT * 
	FROM PERFORMANCES

	-- CREATION DE LA TABLE TUNOVER -- 
	
	CREATE TABLE TURNOVER 
		(
		id_depart SERIAL PRIMARY KEY NOT NULL, 	
		id_employe INT REFERENCES EMPLOYES (ID_EMPLOYE), 
		date_depart DATE, 
		type_depart VARCHAR (20),
		anciennete INT
		);
	
	SELECT * 
	FROM TURNOVER 

-- SCORE MOYEN PAR EMPLOYES --  

	SELECT E.NOM, E.PRENOM,
	ROUND (AVG (P.SCORE), 2) 
	AS SCORE_MOYEN
	FROM EMPLOYES E 
	JOIN PERFORMANCES P ON E.ID_EMPLOYE = P.ID_EMPLOYE
	GROUP BY E.NOM, E.PRENOM 
	ORDER BY SCORE_MOYEN
	LIMIT 10
	
	
	SELECT *
	FROM PERFORM_MOY
	
-- CATEGORIE DE PERFORMANACE -- 

	SELECT  E.NOM, E.PRENOM,
		ROUND (AVG (P.SCORE), 2)
	AS PERFOR_MOY
	CASE 
		WHEN AVG (P.SCORE) < 60 THEN 'FAIBLE'
		WHEN AVG (P.SCORE) BETWEEN 60 AND 80 THEN 'MOYENNE' 
		ELSE 'ELEVE' 

	FROM PERFORMANCES P 
	JOIN EMPLOYES E ON E.ID_EMPLOYE = P.ID_EMPLOYE 
	GROUP BY E.NOM, E.PRENOM 
	ORDER BY PERFOR_MOY

	SELECT *
	FROM PERFORMANCE_CATEGORIE
	
	
	




	